### ISSUE TITLE
One battery has stopped responding 

### ISSUE THREAD

**Issue by tonyvfield** [DanielGallo/GivEnergy-Smart-Home-Display#4]
Hi guys, 
I am not very good at this stuff, so in your reply please assume I am an idiot and then I might understand the answer

I have 2 inverters and 2 batteries connected in plant mode. For about 6 months everything has been working fine but now one of the inverters does not work properly.
Both sets can be seen and controlled by the app and the web interface. but the inv2 on address ....29 does not play ball and no data is found.
The inverter IP addresses are fixed and the stuff does find both inverters on the correct IP address, but that is as far as it gets.
The copy of the log showing the problem is below.
I have checked with GE and both have the correct/same software/firmware. I have done a hard reset with them, no change, I have done a power cycle on HA and no change. 
Ideas please?

2024-09-10 16:39:03,260 - Inv1 - mqtt_client -  [CRITICAL] - Connecting to MQTT broker for control- core-mosquitto
 UPDATE  The latest version of `serve` is 14.2.3
 UPDATE  The latest version of `serve` is 14.2.3
2024-09-10 16:39:06,546 - Inv2 - mqtt_client -  [CRITICAL] - Connecting to MQTT broker for control- core-mosquitto
 INFO  Accepting connections at http://localhost:3042
 INFO  Accepting connections at http://localhost:3043
2024-09-10 16:39:15,391 - Inv2 - read        -  [ERROR   ] - 10 failed inverter reads in a row so removing regCache to force update...
2024-09-10 16:40:43,398 - Inv1 - mqtt_client -  [ERROR   ] - No serial_number found in MQTT queue. MQTT Control not available.
Traceback (most recent call last):
  File "/app/GivTCP_1/mqtt_client.py", line 402, in <module>
    client.loop_forever()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2297, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1686, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2100, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3814, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3934, in _handle_connack
    on_connect(
  File "/app/GivTCP_1/mqtt_client.py", line 386, in on_connect
    client.subscribe(MQTT_Topic+"/control/"+GiV_Settings.serial_number+"/#")
AttributeError: type object 'GiV_Settings' has no attribute 'serial_number'
2024-09-10 16:40:46,694 - Inv2 - mqtt_client -  [ERROR   ] - No serial_number found in MQTT queue. MQTT Control not available.
Traceback (most recent call last):
  File "/app/GivTCP_2/mqtt_client.py", line 402, in <module>

**Comment by DanielGallo** [comment]
Hi! As this relates to the inverter control on the GivTCP side (rather than the web dashboard), I recommend reposting this question in the GivTCP repository: https://github.com/britkat1980/giv_tcp/issues. 
Thanks
